name: Android Firebase Distribution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '17'
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g"
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # --- Validate required secrets (done inside the shell; no 'if:' expression) ---
      - name: Check required secrets
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
        run: |
          if [ -z "$FIREBASE_SERVICE_ACCOUNT_JSON" ]; then
            echo "::error::Missing secret FIREBASE_SERVICE_ACCOUNT_JSON"
            exit 1
          fi
          if [ -z "$FIREBASE_ANDROID_APP_ID" ]; then
            echo "::error::Missing secret FIREBASE_ANDROID_APP_ID"
            exit 1
          fi

      # --- Write Firebase service account JSON to file & export GOOGLE_APPLICATION_CREDENTIALS ---
      - name: Write Firebase service account file
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ci"
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > "$GITHUB_WORKSPACE/ci/firebase-sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/ci/firebase-sa.json" >> $GITHUB_ENV

      # --- Android signing (optional) ---
      - name: Prepare Android signing (optional)
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          set -e
          mkdir -p "$GITHUB_WORKSPACE/ci"

          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "Decoding CI keystore"
            set +e
            printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
            DECODE_RC=$?
            if [ $DECODE_RC -ne 0 ]; then
              printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 -d > "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
              DECODE_RC=$?
            fi
            set -e
            if [ $DECODE_RC -ne 0 ]; then
              echo "::error::Failed to decode ANDROID_KEYSTORE_BASE64. Ensure it's single-line (Linux: 'base64 -w 0 file.jks')."
              exit 1
            fi
            ls -l "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
          else
            echo "No keystore provided; using debug signing (unless Gradle enforces CI signing)."
          fi

          # Export signing env vars for Gradle only if present
          if [ -n "$ANDROID_KEYSTORE_PASSWORD" ]; then
            echo "ANDROID_KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> $GITHUB_ENV
          fi
          if [ -n "$ANDROID_KEY_ALIAS" ]; then
            echo "ANDROID_KEY_ALIAS=$ANDROID_KEY_ALIAS" >> $GITHUB_ENV
          fi
          if [ -n "$ANDROID_KEY_PASSWORD" ]; then
            echo "ANDROID_KEY_PASSWORD=$ANDROID_KEY_PASSWORD" >> $GITHUB_ENV
          fi

      # --- Build Beta (your 'beta' buildType) ---
      - name: Build Beta
        run: ./gradlew :composeApp:assembleBeta --stacktrace --info

      # --- Distribute to Firebase App Distribution ---
      - name: Distribute to Firebase (Beta)
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
        run: |
          if [ -z "$FIREBASE_APP_ID" ]; then
            echo "::error::FIREBASE_APP_ID is empty. Check secret FIREBASE_ANDROID_APP_ID."
            exit 1
          fi

          ./gradlew \
            -PfirebaseAppDistribution.appId="$FIREBASE_APP_ID" \
            -PfirebaseAppDistribution.serviceCredentialsFile="$GITHUB_WORKSPACE/ci/firebase-sa.json" \
            -PfirebaseAppDistribution.releaseNotes="Build $GITHUB_RUN_NUMBER - $GIT_SHA" \
            :composeApp:appDistributionUploadBeta \
            --stacktrace --info