name: Android Firebase Distribution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '17'
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g"
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # --- Firebase Service Account JSON (from secret) ---
      - name: Write Firebase service account file
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ci"
          cat > "$GITHUB_WORKSPACE/ci/firebase-sa.json" << 'JSON'
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          JSON

      - name: Export GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/ci/firebase-sa.json" >> $GITHUB_ENV

      # --- Android signing (from secrets, optional if using debug) ---
      - name: Prepare Android signing
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ci"
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$GITHUB_WORKSPACE/ci/ci-keystore.jks"

      # Export signing passwords for Gradle to read via System.getenv
      - name: Export signing env
        if: ${{ secrets.ANDROID_KEYSTORE_PASSWORD != '' }}
        run: |
          echo "ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_ENV

      # --- Build Beta ---
      - name: Build Beta
        run: ./gradlew :composeApp:assembleBeta

      # --- Upload to Firebase App Distribution ---
      - name: Distribute to Firebase (Beta)
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
        run: |
          ./gradlew \
            -PfirebaseAppDistribution.appId="$FIREBASE_APP_ID" \
            -PfirebaseAppDistribution.serviceCredentialsFile="$GITHUB_WORKSPACE/ci/firebase-sa.json" \
            -PfirebaseAppDistribution.releaseNotes="Build $GITHUB_RUN_NUMBER - $GIT_SHA" \
            :composeApp:appDistributionUploadBeta