name: Android Firebase Distribution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '17'
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g"
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # --- Verify required secrets early ---
      - name: Verify required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" ]; then
            echo "::error::Missing secret FIREBASE_SERVICE_ACCOUNT_JSON"
            exit 1
          fi
          if [ -z "${{ secrets.FIREBASE_ANDROID_APP_ID }}" ]; then
            echo "::error::Missing secret FIREBASE_ANDROID_APP_ID"
            exit 1
          fi

      # --- Firebase Service Account JSON (from secret) ---
      - name: Write Firebase service account file
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ci"
          # Write secret to file
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > "$GITHUB_WORKSPACE/ci/firebase-sa.json"
          # Export for SDKs that look for this
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/ci/firebase-sa.json" >> $GITHUB_ENV
          # Quick sanity check
          test -s "$GITHUB_WORKSPACE/ci/firebase-sa.json" || (echo "::error::firebase-sa.json is empty"; exit 1)

      # --- Prepare Android signing (optional) ---
      # Will only run if secrets exist; otherwise we keep debug signing.
      - name: Prepare Android signing (optional)
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ci"
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "Decoding CI keystore"
            echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
            ls -l "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
          else
            echo "No keystore provided; using debug signing"
          fi
          # Export passwords as env for Gradle (only if present)
          [ -n "$ANDROID_KEYSTORE_PASSWORD" ] && echo "ANDROID_KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> $GITHUB_ENV
          [ -n "$ANDROID_KEY_ALIAS" ] && echo "ANDROID_KEY_ALIAS=$ANDROID_KEY_ALIAS" >> $GITHUB_ENV
          [ -n "$ANDROID_KEY_PASSWORD" ] && echo "ANDROID_KEY_PASSWORD=$ANDROID_KEY_PASSWORD" >> $GITHUB_ENV

      # --- Build Beta variant ---
      - name: Build Beta
        run: ./gradlew :composeApp:assembleBeta --stacktrace --info -Dorg.gradle.configuration-cache=false

      # --- Upload to Firebase App Distribution ---
      - name: Distribute to Firebase (Beta)
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
        run: |
          if [ -z "$FIREBASE_APP_ID" ]; then
            echo "::error::FIREBASE_APP_ID is empty at runtime"
            exit 1
          fi
          ./gradlew \
            -PfirebaseAppDistribution.appId="$FIREBASE_APP_ID" \
            -PfirebaseAppDistribution.serviceCredentialsFile="$GITHUB_WORKSPACE/ci/firebase-sa.json" \
            -PfirebaseAppDistribution.releaseNotes="Build $GITHUB_RUN_NUMBER - $GIT_SHA" \
            :composeApp:appDistributionUploadBeta \
            --stacktrace --info -Dorg.gradle.configuration-cache=false