name: Android Firebase Distribution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g"
      GIT_SHA: ${{ github.sha }}
      GIT_MESSAGE: ${{ github.event.head_commit.message }}
      # (optional) surface secrets as env so Gradle can read them too
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Check required secrets
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
        run: |
          if [ -z "$FIREBASE_SERVICE_ACCOUNT_JSON" ]; then
            echo "::error::Missing secret FIREBASE_SERVICE_ACCOUNT_JSON"
            exit 1
          fi
          if [ -z "$FIREBASE_ANDROID_APP_ID" ]; then
            echo "::error::Missing secret FIREBASE_ANDROID_APP_ID"
            exit 1
          fi

      - name: Write Firebase service account file
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ci"
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > "$GITHUB_WORKSPACE/ci/firebase-sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/ci/firebase-sa.json" >> $GITHUB_ENV

      - name: Prepare Android signing (optional)
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: |
          set -e
          mkdir -p "$GITHUB_WORKSPACE/ci"
          echo "Decoding CI keystore"
          if ! printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$GITHUB_WORKSPACE/ci/ci-keystore.jks"; then
            printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 -d > "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
          fi
          ls -l "$GITHUB_WORKSPACE/ci/ci-keystore.jks"
          [ -n "$ANDROID_KEYSTORE_PASSWORD" ] && echo "ANDROID_KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> $GITHUB_ENV
          [ -n "$ANDROID_KEY_ALIAS" ] && echo "ANDROID_KEY_ALIAS=$ANDROID_KEY_ALIAS" >> $GITHUB_ENV
          [ -n "$ANDROID_KEY_PASSWORD" ] && echo "ANDROID_KEY_PASSWORD=$ANDROID_KEY_PASSWORD" >> $GITHUB_ENV

      - name: Read build type from gradle.properties
        run: |
          if [ -f gradle.properties ]; then
            BT=$(grep -E '^\s*BUILD_TYPE\s*=' gradle.properties | sed 's/.*=\s*//')
          fi
          BT=${BT:-beta}
          echo "BUILD_TYPE=$BT" >> $GITHUB_ENV
          echo "Using BUILD_TYPE=$BT."

      - name: Build (${{ env.BUILD_TYPE }})
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "Building app with buildNumber=$BUILD_NUMBER"
          ./gradlew :composeApp:assemble${{ env.BUILD_TYPE^ }} -PbuildNumber=$BUILD_NUMBER

      - name: Distribute to Firebase (${{ env.BUILD_TYPE }})
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
        run: |
          if [ -z "$FIREBASE_APP_ID" ]; then
            echo "::error::FIREBASE_APP_ID is empty. Check the FIREBASE_ANDROID_APP_ID secret."
            exit 1
          fi
          echo "🚀 Distributing buildNumber=$BUILD_NUMBER"
          ./gradlew \
            -PfirebaseAppDistribution.appId="$FIREBASE_APP_ID" \
            -PfirebaseAppDistribution.serviceCredentialsFile="$GITHUB_WORKSPACE/ci/firebase-sa.json" \
            -PfirebaseAppDistribution.releaseNotes="Commit: $GIT_MESSAGE | Build $GITHUB_RUN_NUMBER - $GIT_SHA" \
            :composeApp:appDistributionUpload${{ env.BUILD_TYPE^ }}