name: Android Firebase Distribution

on:
  push:
    branches: [ main ]           # change to your default branch
  workflow_dispatch:              # allow manual trigger
  # tags:
  #   - 'v*'                      # optionally only on tags

jobs:
  distribute:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '17'
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g"
      # Optional: drive release notes via CI context
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # --- Firebase Service Account JSON (from GitHub secret) ---
      - name: Write Firebase service account file
        run: |
          mkdir -p $GITHUB_WORKSPACE/ci
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > $GITHUB_WORKSPACE/ci/firebase-sa.json
        shell: bash

      - name: Export GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/ci/firebase-sa.json" >> $GITHUB_ENV

      # --- Android signing (optional; skip if using debug keystore) ---
      - name: Prepare Android signing
        if: env.ANDROID_KEYSTORE_PASSWORD != ''
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p $GITHUB_WORKSPACE/ci
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > $GITHUB_WORKSPACE/ci/keystore.jks

      # --- Assemble the Beta APK/AAB ---
      - name: Build Beta
        run: ./gradlew :composeApp:assembleBeta

      # --- Upload to Firebase App Distribution ---
      - name: Distribute to Firebase (Beta)
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}   # 1:1234567890:android:abc...
        run: |
          ./gradlew \
            -PfirebaseAppDistribution.appId=$FIREBASE_APP_ID \
            -PfirebaseAppDistribution.serviceCredentialsFile=$GITHUB_WORKSPACE/ci/firebase-sa.json \
            -PfirebaseAppDistribution.releaseNotes="Build $GITHUB_RUN_NUMBER - $GIT_SHA" \
            :composeApp:appDistributionUploadBeta